### ISSUE TITLE
DMG not handled correctly

### ISSUE THREAD

**Issue by ISSOtm** [NotImplementedLife/Trabant#1]
The demo is mostly playable, but the intro has wrong color (including invisible text), all the cars have the same color, and the main section looks quite glitched out.

**Comment by NotImplementedLife** [comment]
Hi! Thanks for your feedback! This was intended to be a GBC-only ROM and haven't expected it to be run in DMG mode. Should I add a message that warns the user if the ROM doesn't run on GBC?

**Comment by ISSOtm** [comment]
Yeah, preventing the game from running broken on a DMG was one of Nintendo's strict requirements.

**Comment by NotImplementedLife** [comment]
I think I solved it. Here is the new version: https://github.com/NotImplementedLife/Trabant/releases/tag/1.3
